### ISSUE TITLE
error in test.py 

### ISSUE THREAD

**Issue by Jee-King** [daniilidis-group/EV-FlowNet#10]
Hi, I run the test.py but I got some errors, when I run

python test.py --training_instance ev-flownet --test_sequence outdoor_day1 

`2020-03-04 11:05:04.723091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10556 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:0f:00.0, compute capability: 7.0)
Loading data!
Read 787 images
Testing done.
2020-03-04 11:05:07.412942: W tensorflow/core/kernels/queue_base.cc:285] _0_parallel_read/filenames: Skipping cancelled dequeue attempt with queue not closed
2020-03-04 11:05:07.414032: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed
2020-03-04 11:05:07.414954: W tensorflow/core/kernels/queue_base.cc:285] _0_parallel_read/filenames: Skipping cancelled dequeue attempt with queue not closed
2020-03-04 11:05:07.414973: W tensorflow/core/kernels/queue_base.cc:285] _0_parallel_read/filenames: Skipping cancelled dequeue attempt with queue not closed
2020-03-04 11:05:07.416645: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed
2020-03-04 11:05:07.416663: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed
2020-03-04 11:05:07.416672: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed
`

**Comment by Jee-King** [comment]
I can not find the saved result .npz file.

**Comment by Jee-King** [comment]
And when I add the argument --save_test_output, it makes an error,

`
2020-03-04 11:56:32.266636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10556 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:0f:00.0, compute capability: 7.0)
Loading data!
Read 787 images
Testing done.
Saving data to outdoor_day1_output.npz
Traceback (most recent call last):
  File "test.py", line 250, in <module>
    main()
  File "test.py", line 245, in main
    timestamp_loader)
  File "test.py", line 211, in test
    output_flows=np.stack(output_flow_list, axis=0),
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 349, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
`

I find the list _output_flow_list_ and _event_image_list_ both are  [].

**Comment by Jee-King** [comment]
waiting for your apply

**Comment by alexzzhu** [comment]
Hmm unfortunately that error is not too informative. As a sanity check, do you have the tfrecord data in the data/mvsec_data folder? Do you run into the same issue if you try testing on a different sequence?

**Comment by Jee-King** [comment]
I got test data _outdoor_day1_ from google drive your provided. The tfrecode data is in the data/mvsec/outdoor_day1, but the size of tfrecode data is zero. I will download it again.

**Comment by Jee-King** [comment]
The size of tfrecode data of outdoor_day1 your provided is zero. Is it true?

**Comment by alexzzhu** [comment]
Are you downloading the left events from here:
https://drive.google.com/drive/folders/12zDiLY30ZjlkFtJIV1YLJpa-S0xCoysS

Drive says 5GB for me. Are you downloading the right events? I think the grayscale images for that camera were corrupted, so that file may be empty.

**Comment by Jee-King** [comment]
Ok. thank you, I will download it again. So the tfrecode data saves event images?

**Comment by alexzzhu** [comment]
Yes, the event images should be inside the tfrecords. Let me know if you run into any other issues.

**Comment by Jee-King** [comment]
Ok, thank you very much!!

**Comment by Jee-King** [comment]
Hi, could you give some suggestions about how to make the tfrecords data?

**Comment by e-sha** [comment]
> Hi, could you give some suggestions about how to make the tfrecords data?

I found that the simplest way is to use ROS inside docker container.
So I used this docker file
```
FROM ros:latest
MAINTAINER eshalnov@graphics.cs.msu.ru

ENV DEBIAN_FRONTEND "noninteractive"
RUN apt-get update && apt-get install python python-pip ros-melodic-cv-bridge -y
RUN pip install --upgrade setuptools pip
RUN pip install jupyter
RUN pip install tensorflow==1.10.0
WORKDIR /home
CMD jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
```
And inside the container use this [file](https://github.com/daniilidis-group/EV-FlowNet/blob/master/data/extract_rosbag_to_tf.py)  to convert bag-files to tfrecords

**Comment by Jee-King** [comment]
Thanks for your reply. I want to use myself dataset, and I have event.txt file with (x,y,t,p). So could you give me suggestions about how to transform (x,y,t,p) to tfrecodes?

**Comment by Jee-King** [comment]
Hi, I read the _extract_rosbag_to_tf.py_, but it is difficult for me to understand it.  Could you help me to understand each feature? What's the meaning of each feature?

`event_image_tf = tf.train.Example(features=tf.train.Features(feature={
                'image_iter': _int64_feature(event_image_iter),
                'shape': _bytes_feature(
                    image_shape.tobytes()),
                'event_count_images': _bytes_feature(
                    np.array(event_count_images[i:i+max_aug], dtype=np.uint16).tobytes()),
                'event_time_images': _bytes_feature(event_time_images_np.tobytes()),
                'image_times': _bytes_feature(
                    image_times_out.tobytes()),
                'prefix': _bytes_feature(
                    prefix.encode()),
                'cam': _bytes_feature(
                    cam.encode())
            }))`

**Comment by alexzzhu** [comment]
It would probably be easiest to call this function within your code: https://github.com/daniilidis-group/EV-FlowNet/blob/cf801ef5e4b112e08bfe6eac4f0878b1f5aac2fe/data/extract_rosbag_to_tf.py#L21

The inputs are lists, and the function will modify (delete elements) in place.

The features are TF features, and are stored as protocol buffers. You can find more information about this data format here: https://www.tensorflow.org/tutorials/load_data/tfrecord.

**Comment by Jee-King** [comment]
Thanks for your reply. I will try.
