### ISSUE TITLE
 No such file or directory: '/mnt/data/mvsec/outdoor_day2/n_images.txt'

### ISSUE THREAD

**Issue by SeaEastXu** [daniilidis-group/EV-FlowNet#13]
Hi
 There are some problems where I run train.py and test.py
```
$ python train.py --training_instance model1

Loading data!
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    main()
  File "train.py", line 35, in main
    shuffle=True)
  File "/home/xuhaidong/EV-FlowNet/src/data_loader.py", line 206, in get_loader
    sequence)
  File "/home/xuhaidong/EV-FlowNet/src/data_loader.py", line 167, in read_file_paths
    num_ima_file = open(os.path.join(data_folder_path, bag_name, 'n_images.txt'), 'r')
IOError: [Errno 2] No such file or directory: '/mnt/data/mvsec/outdoor_day2/n_images.txt'


```

```
$ python test.py --training_instance ev-flownet --test_sequence outdoor_day1

Loading data!
Traceback (most recent call last):
  File "test.py", line 248, in <module>
    main()
  File "test.py", line 232, in main
    count_only=args.count_only)
  File "/home/xuhaidong/EV-FlowNet/src/data_loader.py", line 206, in get_loader
    sequence)
  File "/home/xuhaidong/EV-FlowNet/src/data_loader.py", line 167, in read_file_paths
    num_ima_file = open(os.path.join(data_folder_path, bag_name, 'n_images.txt'), 'r')
IOError: [Errno 2] No such file or directory: '/mnt/data/mvsec/outdoor_day1/n_images.txt'
```
There is a missing file n_images.txt.How to achieve the n_images.txt?

**Comment by alexzzhu** [comment]
If you can't find it, you can just generate your own txt file. It should have two numbers separated by a space, the number of left camera images and the number of right camera images. An example is here: https://drive.google.com/file/d/1SNtu0b9jBnM3hxTEZiUnrYf80m9owjMD/view?usp=sharing
