### ISSUE TITLE
Cannot get test set to work

### ISSUE THREAD

**Issue by TimoStoff** [daniilidis-group/EV-FlowNet#2]
Hi guys,

I've followed the instructions in the ReadMe for getting the test set to work to the word, but I just spent the afternoon chasing one error after the next, which makes me think I am doing something systematically wrong. The first error I get is:
`Traceback (most recent call last):
  File "test.py", line 223, in <module>
    main()
  File "test.py", line 207, in main
    count_only=args.count_only)
  File "/home/timo/git/EV-FlowNet/src/data_loader.py", line 253, in get_loader
    values = provider.get(keys)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/data/data_provider.py", line 80, in get
    self._validate_items(items)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/data/data_provider.py", line 110, in _validate_items
    raise ValueError('items must be a list or tuple')
ValueError: items must be a list or tuple`

The issue here is that in the line `values = provider.get(keys)` we are passing a `dict_keys` object. So I converted it to a list just to get the next error:
`Traceback (most recent call last):
  File "test.py", line 223, in <module>
    main()
  File "test.py", line 218, in main
    timestamp_loader)
  File "test.py", line 35, in test
    do_batch_norm=not args.no_batch_norm)
  File "/home/timo/git/EV-FlowNet/src/model.py", line 76, in model
    do_batch_norm=do_batch_norm)
  File "/home/timo/git/EV-FlowNet/src/model.py", line 46, in decoder
    data_format=data_format)
  File "/home/timo/git/EV-FlowNet/src/basic_layers.py", line 77, in upsample_conv2d
    mode = 'REFLECT')
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1885, in pad
    tensor, paddings, mode="REFLECT", name=name)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4199, in mirror_pad
    "MirrorPad", input=input, paddings=paddings, mode=mode, name=name)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1731, in __init__
    control_input_ops)
  File "/home/timo/git/EV-FlowNet/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Value for attr 'Tpaddings' of float is not in the list of allowed values: int32, int64`

Anyways, I'm 5 errors down the rabbit hole so to speak and starting to think I must be missing something. Could you please make the ReadMe more comprehensive so that I can get at least something to work? I would be very obliged. Thanks!

**Comment by alexzzhu** [comment]
Which version of TensorFlow are you using?

**Comment by TimoStoff** [comment]
python -c 'import tensorflow as tf; print(tf.__version__)':
1.10.1

**Comment by alexzzhu** [comment]
The code works out of the box for me 1.10.0 with python2. It looks like the issue is python3. The code should work for you if you revert your changes and just run with python2.

**Comment by TimoStoff** [comment]
Hi,
with Python 2 it works:
`2018-10-02 11:39:30.106778: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loading data!
WARNING:tensorflow:From /home/timo/git/EV-FlowNet/venv2/local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/timo/git/EV-FlowNet/venv2/local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Read 787 images
WARNING:tensorflow:From test.py:48: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Testing done. 
2018-10-02 11:39:31.847702: W tensorflow/core/kernels/queue_base.cc:285] _0_parallel_read/filenames: Skipping cancelled dequeue attempt with queue not closed
2018-10-02 11:39:31.847769: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed
2018-10-02 11:39:31.847809: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed
2018-10-02 11:39:31.847874: W tensorflow/core/kernels/queue_base.cc:285] _0_parallel_read/filenames: Skipping cancelled dequeue attempt with queue not closed
2018-10-02 11:39:31.847896: W tensorflow/core/kernels/queue_base.cc:285] _0_parallel_read/filenames: Skipping cancelled dequeue attempt with queue not closed
2018-10-02 11:39:31.847937: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed
2018-10-02 11:39:31.847950: W tensorflow/core/kernels/queue_base.cc:285] _1_parallel_read/common_queue: Skipping cancelled dequeue attempt with queue not closed`

You may want to mention this in the ReadMe. Also, I think it would be helpful to include an example of visualising the output flow vectors, at the moment the testing command doesn't apparently do anything...just a thought :)

**Comment by alexzzhu** [comment]
The visualization should show up if you add the command line argument --test_plot. It's not activated by default to allow the test code to be run on servers without display capabilities.

**Comment by TimoStoff** [comment]
Yeah, I had already tried that, it says in the ReadMe. The problem I have is that the visualisation windows flashes up for a short moment, then closes. The output on my terminal is:
`2018-10-03 08:30:31.732030: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loading data!
WARNING:tensorflow:From /home/timo/git/EV-FlowNet/venv2/local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/timo/git/EV-FlowNet/venv2/local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Read 787 images
WARNING:tensorflow:From test.py:48: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Testing done. `
Do you have any suggestions? Can I get the testing script to output the flow vectors into a file at least, so that I can evaluate them another way?

**Comment by alexzzhu** [comment]
Hmm that is strange. It seems like you're not actually reading in any input data from that output. If it works correctly, it should periodically print the AEE. The visualization uses OpenCV, which shouldn't have any compatibility issues. Which sequence are you testing on? 

Yes, I can add some code to optionally save the flow to a npz file.

**Comment by alexzzhu** [comment]
Apologies for the delay, but the predicted flow, along with event histograms and GT flows can now be saved as a npz file with the option --save_test_output.
