### ISSUE TITLE
error in test.py at sess.run()

### ISSUE THREAD

**Issue by valerdi** [daniilidis-group/EV-FlowNet#9]
hi, i'm trying the test.py but i'm having some errors, when i run

python test.py --training_instance ev-flownet --test_sequence outdoor_day1 --save_test_output

Traceback (most recent call last):
  File "test.py", line 251, in <module>
    main()
  File "test.py", line 246, in main
    timestamp_loader)
  File "test.py", line 214, in test
    output_flows=np.stack(output_flow_list, axis=0),
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 349, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

going into the code i found that the code breaks from
   while not coord.should_stop()
in the first cycle because is getting an error in

sess.run([flow_dict,
                                             prev_image_loader,
                                             next_image_loader,
                                             event_image_loader,
                                             timestamp_loader])

the error is as follows:

FIFOQueue '_3_batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_DOUBLE], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/fifo_queue, batch/n)]]

Caused by op u'batch', defined at:
  File "test.py", line 252, in <module>
    main()
  File "test.py", line 236, in main
    count_only=args.count_only)
  File "/learning/EV-FlowNet/src/data_loader.py", line 308, in get_loader
    capacity=10*batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 988, in batch
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 762, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 476, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_3_batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_DOUBLE], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/fifo_queue, batch/n)]]

My configuration is TF 1.10.0 and Python 2 inside the official docker. I'm using the pre-trained model  and the outdoor_day1 converted data that you provided.

**Comment by valerdi** [comment]
SOLVED: left_event_images.tfrecord file was missing from the folder /data/mvsec_data/outdoor_day1/

**Comment by Jee-King** [comment]
@valerdi  
Hi, did you run test,py successfully？When I run test.py, it makes an error [https://github.com/daniilidis-group/EV-FlowNet/issues/10](url)

And I read this paper. it seems that at training time, the network is provided with the event timestamp images, as well as a pair of grayscale images for calculating optical flow. However, why this test code only uses gray images as input(the test dataset outdoor_1 only contains gray images )?
Wainting for your apply. Thanks!

**Comment by alexzzhu** [comment]
Sorry, @valerdi for not seeing this earlier! I'm glad you were able to resolve your issue. @Jee-King  I'll try resolve your issue in #10.
